from typing import Protocol, Self


class Comparable(Protocol):
    def __lt__(self, other: Self, /) -> bool: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __gt__(self, other: Self, /) -> bool: ...
