class DomainException(Exception):
    def __init__(self, msg: str) -> None:
        super().__init__(msg)
        self.msg: str = msg


class NotFoundError(DomainException): ...


class UnknownInformationError(DomainException): ...


class VehicleError(DomainException): ...


class TransportError(DomainException): ...


class WrongDestinationError(TransportError): ...


class BudgetLimitExceededError(DomainException): ...


class NotEnoughMoneyError(DomainException): ...


class FrozenAccountError(DomainException): ...


class TransactionError(DomainException): ...


class ConverterError(DomainException): ...


class AccountClosingError(DomainException): ...


class ProductionUnitError(DomainException): ...


class ProductionLineError(DomainException): ...


class FactoryError(DomainException): ...


class InvalidProductError(DomainException): ...


class NotEnoughItemError(DomainException): ...


class SaleOrderError(DomainException): ...


class PurchaseOrderError(DomainException): ...


class AdvertisementChannelExistedError(DomainException): ...
